System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system",
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  paths: {
    "*": "src/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "kendo-sdk/*": "kendo-sdk/*",
    "samplesJSON/*": "https://aurelia-ui-toolkits.github.io/aurelia-kendoui-samples/*"
  },
  meta: {
    "showdown/dist/showdown.min.js": {
      "format": "global"
    }
  },
  map: {
    "aurelia-after-attached-plugin": "github:aurelia-ui-toolkits/aurelia-after-attached-plugin@0.1.0",
    "aurelia-binding": "npm:aurelia-binding@2.5.2",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.1",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.5.2",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.3",
    "aurelia-framework": "npm:aurelia-framework@1.3.1",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.4.0",
    "aurelia-http-client": "npm:aurelia-http-client@1.3.1",
    "aurelia-kendoui-bridge": "npm:aurelia-kendoui-bridge@1.10.0",
    "aurelia-loader": "npm:aurelia-loader@1.0.2",
    "aurelia-logging": "npm:aurelia-logging@1.5.2",
    "aurelia-metadata": "npm:aurelia-metadata@1.0.6",
    "aurelia-pal": "npm:aurelia-pal@1.8.2",
    "aurelia-router": "npm:aurelia-router@1.7.1",
    "aurelia-task-queue": "npm:aurelia-task-queue@1.3.3",
    "aurelia-templating": "npm:aurelia-templating@1.10.3",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.13.0",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "bootstrap": "github:twbs/bootstrap@3.3.6",
    "core-js": "npm:core-js@1.2.7",
    "css": "github:systemjs/plugin-css@0.1.20",
    "font-awesome": "npm:font-awesome@4.6.3",
    "google/code-prettify": "github:google/code-prettify@master",
    "jquery": "@empty",
    "json": "github:systemjs/plugin-json@0.1.2",
    "prism": "github:PrismJS/prism@1.3.0",
    "showdown": "npm:showdown@1.9.1",
    "showdown-prettify": "npm:showdown-prettify@1.3.0",
    "text": "github:systemjs/plugin-text@0.0.4",
    "github:aurelia-ui-toolkits/aurelia-after-attached-plugin@0.1.0": {
      "aurelia-task-queue": "npm:aurelia-task-queue@1.3.3",
      "aurelia-templating": "npm:aurelia-templating@1.10.3"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.5.0"
    },
    "github:jspm/nodelibs-buffer@0.1.1": {
      "buffer": "npm:buffer@5.4.3"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.10"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:ansi-styles@3.2.1": {
      "color-convert": "npm:color-convert@1.9.3"
    },
    "npm:assert@1.5.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.1",
      "object-assign": "npm:object-assign@4.1.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-binding@2.5.2": {
      "aurelia-logging": "npm:aurelia-logging@1.5.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.6",
      "aurelia-pal": "npm:aurelia-pal@1.8.2",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.3.3"
    },
    "npm:aurelia-bootstrapper@1.0.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.3",
      "aurelia-framework": "npm:aurelia-framework@1.3.1",
      "aurelia-history": "npm:aurelia-history@1.2.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.4.0",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.2.1",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.8.2",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.8.1",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.3.4",
      "aurelia-router": "npm:aurelia-router@1.7.1",
      "aurelia-templating": "npm:aurelia-templating@1.10.3",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.5.3",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.13.0",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.4.0"
    },
    "npm:aurelia-dependency-injection@1.5.2": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.6",
      "aurelia-pal": "npm:aurelia-pal@1.8.2"
    },
    "npm:aurelia-event-aggregator@1.0.3": {
      "aurelia-logging": "npm:aurelia-logging@1.5.2"
    },
    "npm:aurelia-framework@1.3.1": {
      "aurelia-binding": "npm:aurelia-binding@2.5.2",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.5.2",
      "aurelia-loader": "npm:aurelia-loader@1.0.2",
      "aurelia-logging": "npm:aurelia-logging@1.5.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.6",
      "aurelia-pal": "npm:aurelia-pal@1.8.2",
      "aurelia-path": "npm:aurelia-path@1.1.5",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.3.3",
      "aurelia-templating": "npm:aurelia-templating@1.10.3"
    },
    "npm:aurelia-history-browser@1.4.0": {
      "aurelia-history": "npm:aurelia-history@1.2.1",
      "aurelia-pal": "npm:aurelia-pal@1.8.2"
    },
    "npm:aurelia-http-client@1.3.1": {
      "aurelia-pal": "npm:aurelia-pal@1.8.2",
      "aurelia-path": "npm:aurelia-path@1.1.5"
    },
    "npm:aurelia-kendoui-bridge@1.10.0": {
      "aurelia-binding": "npm:aurelia-binding@2.5.2",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.5.2",
      "aurelia-logging": "npm:aurelia-logging@1.5.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.6",
      "aurelia-pal": "npm:aurelia-pal@1.8.2",
      "aurelia-router": "npm:aurelia-router@1.7.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.3.3",
      "aurelia-templating": "npm:aurelia-templating@1.10.3",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.13.0"
    },
    "npm:aurelia-loader-default@1.2.1": {
      "aurelia-loader": "npm:aurelia-loader@1.0.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.6",
      "aurelia-pal": "npm:aurelia-pal@1.8.2"
    },
    "npm:aurelia-loader@1.0.2": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.6",
      "aurelia-path": "npm:aurelia-path@1.1.5"
    },
    "npm:aurelia-logging-console@1.1.1": {
      "aurelia-logging": "npm:aurelia-logging@1.5.2"
    },
    "npm:aurelia-metadata@1.0.6": {
      "aurelia-pal": "npm:aurelia-pal@1.8.2"
    },
    "npm:aurelia-pal-browser@1.8.1": {
      "aurelia-pal": "npm:aurelia-pal@1.8.2"
    },
    "npm:aurelia-polyfills@1.3.4": {
      "aurelia-pal": "npm:aurelia-pal@1.8.2"
    },
    "npm:aurelia-route-recognizer@1.3.2": {
      "aurelia-path": "npm:aurelia-path@1.1.5"
    },
    "npm:aurelia-router@1.7.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.5.2",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.3",
      "aurelia-history": "npm:aurelia-history@1.2.1",
      "aurelia-logging": "npm:aurelia-logging@1.5.2",
      "aurelia-path": "npm:aurelia-path@1.1.5",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.3.2"
    },
    "npm:aurelia-task-queue@1.3.3": {
      "aurelia-pal": "npm:aurelia-pal@1.8.2"
    },
    "npm:aurelia-templating-binding@1.5.3": {
      "aurelia-binding": "npm:aurelia-binding@2.5.2",
      "aurelia-logging": "npm:aurelia-logging@1.5.2",
      "aurelia-templating": "npm:aurelia-templating@1.10.3"
    },
    "npm:aurelia-templating-resources@1.13.0": {
      "aurelia-binding": "npm:aurelia-binding@2.5.2",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.5.2",
      "aurelia-loader": "npm:aurelia-loader@1.0.2",
      "aurelia-logging": "npm:aurelia-logging@1.5.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.6",
      "aurelia-pal": "npm:aurelia-pal@1.8.2",
      "aurelia-path": "npm:aurelia-path@1.1.5",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.3.3",
      "aurelia-templating": "npm:aurelia-templating@1.10.3"
    },
    "npm:aurelia-templating-router@1.4.0": {
      "aurelia-binding": "npm:aurelia-binding@2.5.2",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.5.2",
      "aurelia-logging": "npm:aurelia-logging@1.5.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.6",
      "aurelia-pal": "npm:aurelia-pal@1.8.2",
      "aurelia-path": "npm:aurelia-path@1.1.5",
      "aurelia-router": "npm:aurelia-router@1.7.1",
      "aurelia-templating": "npm:aurelia-templating@1.10.3"
    },
    "npm:aurelia-templating@1.10.3": {
      "aurelia-binding": "npm:aurelia-binding@2.5.2",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.5.2",
      "aurelia-loader": "npm:aurelia-loader@1.0.2",
      "aurelia-logging": "npm:aurelia-logging@1.5.2",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.6",
      "aurelia-pal": "npm:aurelia-pal@1.8.2",
      "aurelia-path": "npm:aurelia-path@1.1.5",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.3.3"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@5.4.3": {
      "base64-js": "npm:base64-js@1.3.1",
      "ieee754": "npm:ieee754@1.1.13"
    },
    "npm:cliui@5.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "string-width": "npm:string-width@3.1.0",
      "strip-ansi": "npm:strip-ansi@5.2.0",
      "wrap-ansi": "npm:wrap-ansi@5.1.0"
    },
    "npm:color-convert@1.9.3": {
      "color-name": "npm:color-name@1.1.3"
    },
    "npm:color-name@1.1.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:core-js@1.2.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:find-up@3.0.0": {
      "locate-path": "npm:locate-path@3.0.0",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:font-awesome@4.6.3": {
      "css": "github:systemjs/plugin-css@0.1.20"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:locate-path@3.0.0": {
      "p-locate": "npm:p-locate@3.0.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "path-exists": "npm:path-exists@3.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:p-limit@2.2.1": {
      "p-try": "npm:p-try@2.2.0"
    },
    "npm:p-locate@3.0.0": {
      "p-limit": "npm:p-limit@2.2.1"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-exists@3.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:process@0.11.10": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:require-directory@2.1.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:require-main-filename@2.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:set-blocking@2.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:showdown-prettify@1.3.0": {
      "showdown": "npm:showdown@1.9.1"
    },
    "npm:showdown@1.9.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "yargs": "npm:yargs@14.2.1"
    },
    "npm:string-width@3.1.0": {
      "emoji-regex": "npm:emoji-regex@7.0.3",
      "is-fullwidth-code-point": "npm:is-fullwidth-code-point@2.0.0",
      "strip-ansi": "npm:strip-ansi@5.2.0"
    },
    "npm:strip-ansi@5.2.0": {
      "ansi-regex": "npm:ansi-regex@4.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:wrap-ansi@5.1.0": {
      "ansi-styles": "npm:ansi-styles@3.2.1",
      "string-width": "npm:string-width@3.1.0",
      "strip-ansi": "npm:strip-ansi@5.2.0"
    },
    "npm:y18n@4.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:yargs-parser@15.0.0": {
      "camelcase": "npm:camelcase@5.3.1",
      "decamelize": "npm:decamelize@1.2.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:yargs@14.2.1": {
      "cliui": "npm:cliui@5.0.0",
      "decamelize": "npm:decamelize@1.2.0",
      "find-up": "npm:find-up@3.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "get-caller-file": "npm:get-caller-file@2.0.5",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "require-directory": "npm:require-directory@2.1.1",
      "require-main-filename": "npm:require-main-filename@2.0.0",
      "set-blocking": "npm:set-blocking@2.0.0",
      "string-width": "npm:string-width@3.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "which-module": "npm:which-module@2.0.0",
      "y18n": "npm:y18n@4.0.0",
      "yargs-parser": "npm:yargs-parser@15.0.0"
    }
  },
  bundles: {
    "app-build-4218093b23.js": [
      "about/about.html!github:systemjs/plugin-text@0.0.4.js",
      "about/about.js",
      "about/kendo-bridge-init.html!github:systemjs/plugin-text@0.0.4.js",
      "about/kendo-bridge-viewmodel.js",
      "about/kendo-standard-init.html!github:systemjs/plugin-text@0.0.4.js",
      "app.html!github:systemjs/plugin-text@0.0.4.js",
      "app.js",
      "github:PrismJS/prism@1.3.0.js",
      "github:PrismJS/prism@1.3.0/prism.js",
      "github:aurelia-ui-toolkits/aurelia-after-attached-plugin@0.1.0.js",
      "github:aurelia-ui-toolkits/aurelia-after-attached-plugin@0.1.0/aurelia-after-attached-plugin.js",
      "github:aurelia-ui-toolkits/aurelia-after-attached-plugin@0.1.0/index.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "github:systemjs/plugin-css@0.1.20.js",
      "github:systemjs/plugin-css@0.1.20/css.js",
      "github:systemjs/plugin-json@0.1.2.js",
      "github:systemjs/plugin-json@0.1.2/json.js",
      "github:systemjs/plugin-text@0.0.4.js",
      "github:systemjs/plugin-text@0.0.4/text.js",
      "github:twbs/bootstrap@3.3.6.js",
      "github:twbs/bootstrap@3.3.6/css/bootstrap.css!github:systemjs/plugin-text@0.0.4.js",
      "github:twbs/bootstrap@3.3.6/js/bootstrap.js",
      "installation/installation.html!github:systemjs/plugin-text@0.0.4.js",
      "installation/installation.js",
      "main.js",
      "nav-bar.html!github:systemjs/plugin-text@0.0.4.js",
      "nav-bar.js",
      "npm:aurelia-binding@2.5.2.js",
      "npm:aurelia-binding@2.5.2/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.1.js",
      "npm:aurelia-bootstrapper@1.0.1/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.5.2.js",
      "npm:aurelia-dependency-injection@1.5.2/aurelia-dependency-injection.js",
      "npm:aurelia-event-aggregator@1.0.3.js",
      "npm:aurelia-event-aggregator@1.0.3/aurelia-event-aggregator.js",
      "npm:aurelia-framework@1.3.1.js",
      "npm:aurelia-framework@1.3.1/aurelia-framework.js",
      "npm:aurelia-history-browser@1.4.0.js",
      "npm:aurelia-history-browser@1.4.0/aurelia-history-browser.js",
      "npm:aurelia-history@1.2.1.js",
      "npm:aurelia-history@1.2.1/aurelia-history.js",
      "npm:aurelia-http-client@1.3.1.js",
      "npm:aurelia-http-client@1.3.1/aurelia-http-client.js",
      "npm:aurelia-kendoui-bridge@1.10.0.js",
      "npm:aurelia-kendoui-bridge@1.10.0/autocomplete/autocomplete.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/autocomplete/autocomplete.js",
      "npm:aurelia-kendoui-bridge@1.10.0/barcode/barcode.js",
      "npm:aurelia-kendoui-bridge@1.10.0/button/button.js",
      "npm:aurelia-kendoui-bridge@1.10.0/buttongroup/buttongroup.js",
      "npm:aurelia-kendoui-bridge@1.10.0/calendar/calendar.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/calendar/calendar.js",
      "npm:aurelia-kendoui-bridge@1.10.0/chart/chart.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/chart/chart.js",
      "npm:aurelia-kendoui-bridge@1.10.0/chart/sparkline.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/chart/sparkline.js",
      "npm:aurelia-kendoui-bridge@1.10.0/chart/stock.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/chart/stock.js",
      "npm:aurelia-kendoui-bridge@1.10.0/chart/treemap.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/chart/treemap.js",
      "npm:aurelia-kendoui-bridge@1.10.0/chat/chat.js",
      "npm:aurelia-kendoui-bridge@1.10.0/colorpalette/colorpalette.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/colorpalette/colorpalette.js",
      "npm:aurelia-kendoui-bridge@1.10.0/colorpicker/colorpicker.js",
      "npm:aurelia-kendoui-bridge@1.10.0/combobox/combobox.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/combobox/combobox.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/bindables.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/constants.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/control-properties.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/decorators.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/notify-binding-behavior.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/observer.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/options-builder.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/template-compiler.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/template-gatherer.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/template.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/util.js",
      "npm:aurelia-kendoui-bridge@1.10.0/common/widget-base.js",
      "npm:aurelia-kendoui-bridge@1.10.0/config-builder.js",
      "npm:aurelia-kendoui-bridge@1.10.0/contextmenu/contextmenu.js",
      "npm:aurelia-kendoui-bridge@1.10.0/dateinput/dateinput.js",
      "npm:aurelia-kendoui-bridge@1.10.0/datepicker/datepicker.js",
      "npm:aurelia-kendoui-bridge@1.10.0/daterangepicker/daterangepicker.js",
      "npm:aurelia-kendoui-bridge@1.10.0/datetimepicker/datetimepicker.js",
      "npm:aurelia-kendoui-bridge@1.10.0/diagram/diagram.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/diagram/diagram.js",
      "npm:aurelia-kendoui-bridge@1.10.0/dialog/dialog.js",
      "npm:aurelia-kendoui-bridge@1.10.0/draggable/draggable.js",
      "npm:aurelia-kendoui-bridge@1.10.0/drop-target/drop-target-area.js",
      "npm:aurelia-kendoui-bridge@1.10.0/drop-target/drop-target.js",
      "npm:aurelia-kendoui-bridge@1.10.0/dropdownlist/dropdownlist.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/dropdownlist/dropdownlist.js",
      "npm:aurelia-kendoui-bridge@1.10.0/dropdowntree/dropdowntree.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/dropdowntree/dropdowntree.js",
      "npm:aurelia-kendoui-bridge@1.10.0/editor/editor.js",
      "npm:aurelia-kendoui-bridge@1.10.0/filter-menu/filter-menu.js",
      "npm:aurelia-kendoui-bridge@1.10.0/flatcolorpicker/flatcolorpicker.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/flatcolorpicker/flatcolorpicker.js",
      "npm:aurelia-kendoui-bridge@1.10.0/gantt/gantt-col.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/gantt/gantt-col.js",
      "npm:aurelia-kendoui-bridge@1.10.0/gantt/gantt.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/gantt/gantt.js",
      "npm:aurelia-kendoui-bridge@1.10.0/gauges/arc-gauge.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/gauges/arc-gauge.js",
      "npm:aurelia-kendoui-bridge@1.10.0/gauges/linear-gauge.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/gauges/linear-gauge.js",
      "npm:aurelia-kendoui-bridge@1.10.0/gauges/radial-gauge.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/gauges/radial-gauge.js",
      "npm:aurelia-kendoui-bridge@1.10.0/grid/col.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/grid/col.js",
      "npm:aurelia-kendoui-bridge@1.10.0/grid/grid-command.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/grid/grid-command.js",
      "npm:aurelia-kendoui-bridge@1.10.0/grid/grid-toolbar.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/grid/grid-toolbar.js",
      "npm:aurelia-kendoui-bridge@1.10.0/grid/grid.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/grid/grid.js",
      "npm:aurelia-kendoui-bridge@1.10.0/index.js",
      "npm:aurelia-kendoui-bridge@1.10.0/listbox/listbox.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/listbox/listbox.js",
      "npm:aurelia-kendoui-bridge@1.10.0/listview/listview.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/listview/listview.js",
      "npm:aurelia-kendoui-bridge@1.10.0/map/map.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/map/map.js",
      "npm:aurelia-kendoui-bridge@1.10.0/maskedtextbox/maskedtextbox.js",
      "npm:aurelia-kendoui-bridge@1.10.0/mediaplayer/mediaplayer.js",
      "npm:aurelia-kendoui-bridge@1.10.0/menu/menu.js",
      "npm:aurelia-kendoui-bridge@1.10.0/multiselect/multiselect.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/multiselect/multiselect.js",
      "npm:aurelia-kendoui-bridge@1.10.0/notification/notification-template.js",
      "npm:aurelia-kendoui-bridge@1.10.0/notification/notification.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/notification/notification.js",
      "npm:aurelia-kendoui-bridge@1.10.0/numerictextbox/numerictextbox.js",
      "npm:aurelia-kendoui-bridge@1.10.0/pager/pager.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/pager/pager.js",
      "npm:aurelia-kendoui-bridge@1.10.0/panelbar/panelbar.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/panelbar/panelbar.js",
      "npm:aurelia-kendoui-bridge@1.10.0/pdf/pdf.js",
      "npm:aurelia-kendoui-bridge@1.10.0/pivotgrid/pivotconfigurator.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/pivotgrid/pivotconfigurator.js",
      "npm:aurelia-kendoui-bridge@1.10.0/pivotgrid/pivotgrid.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/pivotgrid/pivotgrid.js",
      "npm:aurelia-kendoui-bridge@1.10.0/popup/popup.js",
      "npm:aurelia-kendoui-bridge@1.10.0/progressbar/progressbar.js",
      "npm:aurelia-kendoui-bridge@1.10.0/qrcode/qrcode.js",
      "npm:aurelia-kendoui-bridge@1.10.0/rangeslider/rangeslider.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/rangeslider/rangeslider.js",
      "npm:aurelia-kendoui-bridge@1.10.0/responsivepanel/responsivepanel.js",
      "npm:aurelia-kendoui-bridge@1.10.0/scheduler/scheduler.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/scheduler/scheduler.js",
      "npm:aurelia-kendoui-bridge@1.10.0/scrollview/scrollview.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/scrollview/scrollview.js",
      "npm:aurelia-kendoui-bridge@1.10.0/slider/slider.js",
      "npm:aurelia-kendoui-bridge@1.10.0/sortable/sortable.js",
      "npm:aurelia-kendoui-bridge@1.10.0/splitter/splitter.js",
      "npm:aurelia-kendoui-bridge@1.10.0/spreadsheet/spreadsheet.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/spreadsheet/spreadsheet.js",
      "npm:aurelia-kendoui-bridge@1.10.0/switch/switch.js",
      "npm:aurelia-kendoui-bridge@1.10.0/tabstrip/tabstrip.js",
      "npm:aurelia-kendoui-bridge@1.10.0/timepicker/timepicker.js",
      "npm:aurelia-kendoui-bridge@1.10.0/toolbar/toolbar-item-button.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/toolbar/toolbar-item-button.js",
      "npm:aurelia-kendoui-bridge@1.10.0/toolbar/toolbar-item.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/toolbar/toolbar-item.js",
      "npm:aurelia-kendoui-bridge@1.10.0/toolbar/toolbar.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/toolbar/toolbar.js",
      "npm:aurelia-kendoui-bridge@1.10.0/tooltip/tooltip.js",
      "npm:aurelia-kendoui-bridge@1.10.0/treelist/tree-col.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/treelist/tree-col.js",
      "npm:aurelia-kendoui-bridge@1.10.0/treelist/treelist.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/treelist/treelist.js",
      "npm:aurelia-kendoui-bridge@1.10.0/treeview/treeview.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/treeview/treeview.js",
      "npm:aurelia-kendoui-bridge@1.10.0/upload/upload.html!github:systemjs/plugin-text@0.0.4.js",
      "npm:aurelia-kendoui-bridge@1.10.0/upload/upload.js",
      "npm:aurelia-kendoui-bridge@1.10.0/validator/validator.js",
      "npm:aurelia-kendoui-bridge@1.10.0/valueconverters/valueconverters.js",
      "npm:aurelia-kendoui-bridge@1.10.0/version.js",
      "npm:aurelia-kendoui-bridge@1.10.0/window/window.js",
      "npm:aurelia-loader-default@1.2.1.js",
      "npm:aurelia-loader-default@1.2.1/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.2.js",
      "npm:aurelia-loader@1.0.2/aurelia-loader.js",
      "npm:aurelia-logging-console@1.1.1.js",
      "npm:aurelia-logging-console@1.1.1/aurelia-logging-console.js",
      "npm:aurelia-logging@1.5.2.js",
      "npm:aurelia-logging@1.5.2/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.6.js",
      "npm:aurelia-metadata@1.0.6/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.8.1.js",
      "npm:aurelia-pal-browser@1.8.1/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.8.2.js",
      "npm:aurelia-pal@1.8.2/aurelia-pal.js",
      "npm:aurelia-path@1.1.5.js",
      "npm:aurelia-path@1.1.5/aurelia-path.js",
      "npm:aurelia-polyfills@1.3.4.js",
      "npm:aurelia-polyfills@1.3.4/aurelia-polyfills.js",
      "npm:aurelia-route-recognizer@1.3.2.js",
      "npm:aurelia-route-recognizer@1.3.2/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.7.1.js",
      "npm:aurelia-router@1.7.1/aurelia-router.js",
      "npm:aurelia-task-queue@1.3.3.js",
      "npm:aurelia-task-queue@1.3.3/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.5.3.js",
      "npm:aurelia-templating-binding@1.5.3/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.13.0.js",
      "npm:aurelia-templating-resources@1.13.0/aurelia-templating-resources.js",
      "npm:aurelia-templating-router@1.4.0.js",
      "npm:aurelia-templating-router@1.4.0/aurelia-templating-router.js",
      "npm:aurelia-templating@1.10.3.js",
      "npm:aurelia-templating@1.10.3/aurelia-templating.js",
      "npm:babel-core@5.8.38.js",
      "npm:babel-core@5.8.38/browser.js",
      "npm:core-js@1.2.7/library/core.js",
      "npm:core-js@1.2.7/library/core/_.js",
      "npm:core-js@1.2.7/library/core/delay.js",
      "npm:core-js@1.2.7/library/core/dict.js",
      "npm:core-js@1.2.7/library/core/function.js",
      "npm:core-js@1.2.7/library/core/index.js",
      "npm:core-js@1.2.7/library/core/log.js",
      "npm:core-js@1.2.7/library/core/number.js",
      "npm:core-js@1.2.7/library/core/object.js",
      "npm:core-js@1.2.7/library/core/string.js",
      "npm:core-js@1.2.7/library/es5.js",
      "npm:core-js@1.2.7/library/es5/index.js",
      "npm:core-js@1.2.7/library/es6.js",
      "npm:core-js@1.2.7/library/es6/array.js",
      "npm:core-js@1.2.7/library/es6/function.js",
      "npm:core-js@1.2.7/library/es6/index.js",
      "npm:core-js@1.2.7/library/es6/map.js",
      "npm:core-js@1.2.7/library/es6/math.js",
      "npm:core-js@1.2.7/library/es6/number.js",
      "npm:core-js@1.2.7/library/es6/object.js",
      "npm:core-js@1.2.7/library/es6/promise.js",
      "npm:core-js@1.2.7/library/es6/reflect.js",
      "npm:core-js@1.2.7/library/es6/regexp.js",
      "npm:core-js@1.2.7/library/es6/set.js",
      "npm:core-js@1.2.7/library/es6/string.js",
      "npm:core-js@1.2.7/library/es6/symbol.js",
      "npm:core-js@1.2.7/library/es6/weak-map.js",
      "npm:core-js@1.2.7/library/es6/weak-set.js",
      "npm:core-js@1.2.7/library/es7.js",
      "npm:core-js@1.2.7/library/es7/array.js",
      "npm:core-js@1.2.7/library/es7/index.js",
      "npm:core-js@1.2.7/library/es7/map.js",
      "npm:core-js@1.2.7/library/es7/object.js",
      "npm:core-js@1.2.7/library/es7/regexp.js",
      "npm:core-js@1.2.7/library/es7/set.js",
      "npm:core-js@1.2.7/library/es7/string.js",
      "npm:core-js@1.2.7/library/fn/_.js",
      "npm:core-js@1.2.7/library/fn/array.js",
      "npm:core-js@1.2.7/library/fn/array/concat.js",
      "npm:core-js@1.2.7/library/fn/array/copy-within.js",
      "npm:core-js@1.2.7/library/fn/array/entries.js",
      "npm:core-js@1.2.7/library/fn/array/every.js",
      "npm:core-js@1.2.7/library/fn/array/fill.js",
      "npm:core-js@1.2.7/library/fn/array/filter.js",
      "npm:core-js@1.2.7/library/fn/array/find-index.js",
      "npm:core-js@1.2.7/library/fn/array/find.js",
      "npm:core-js@1.2.7/library/fn/array/for-each.js",
      "npm:core-js@1.2.7/library/fn/array/from.js",
      "npm:core-js@1.2.7/library/fn/array/includes.js",
      "npm:core-js@1.2.7/library/fn/array/index-of.js",
      "npm:core-js@1.2.7/library/fn/array/index.js",
      "npm:core-js@1.2.7/library/fn/array/iterator.js",
      "npm:core-js@1.2.7/library/fn/array/join.js",
      "npm:core-js@1.2.7/library/fn/array/keys.js",
      "npm:core-js@1.2.7/library/fn/array/last-index-of.js",
      "npm:core-js@1.2.7/library/fn/array/map.js",
      "npm:core-js@1.2.7/library/fn/array/of.js",
      "npm:core-js@1.2.7/library/fn/array/pop.js",
      "npm:core-js@1.2.7/library/fn/array/push.js",
      "npm:core-js@1.2.7/library/fn/array/reduce-right.js",
      "npm:core-js@1.2.7/library/fn/array/reduce.js",
      "npm:core-js@1.2.7/library/fn/array/reverse.js",
      "npm:core-js@1.2.7/library/fn/array/shift.js",
      "npm:core-js@1.2.7/library/fn/array/slice.js",
      "npm:core-js@1.2.7/library/fn/array/some.js",
      "npm:core-js@1.2.7/library/fn/array/sort.js",
      "npm:core-js@1.2.7/library/fn/array/splice.js",
      "npm:core-js@1.2.7/library/fn/array/unshift.js",
      "npm:core-js@1.2.7/library/fn/array/values.js",
      "npm:core-js@1.2.7/library/fn/clear-immediate.js",
      "npm:core-js@1.2.7/library/fn/delay.js",
      "npm:core-js@1.2.7/library/fn/dict.js",
      "npm:core-js@1.2.7/library/fn/function.js",
      "npm:core-js@1.2.7/library/fn/function/has-instance.js",
      "npm:core-js@1.2.7/library/fn/function/index.js",
      "npm:core-js@1.2.7/library/fn/function/name.js",
      "npm:core-js@1.2.7/library/fn/function/part.js",
      "npm:core-js@1.2.7/library/fn/get-iterator-method.js",
      "npm:core-js@1.2.7/library/fn/get-iterator.js",
      "npm:core-js@1.2.7/library/fn/html-collection.js",
      "npm:core-js@1.2.7/library/fn/html-collection/index.js",
      "npm:core-js@1.2.7/library/fn/html-collection/iterator.js",
      "npm:core-js@1.2.7/library/fn/is-iterable.js",
      "npm:core-js@1.2.7/library/fn/json/stringify.js",
      "npm:core-js@1.2.7/library/fn/log.js",
      "npm:core-js@1.2.7/library/fn/map.js",
      "npm:core-js@1.2.7/library/fn/math.js",
      "npm:core-js@1.2.7/library/fn/math/acosh.js",
      "npm:core-js@1.2.7/library/fn/math/asinh.js",
      "npm:core-js@1.2.7/library/fn/math/atanh.js",
      "npm:core-js@1.2.7/library/fn/math/cbrt.js",
      "npm:core-js@1.2.7/library/fn/math/clz32.js",
      "npm:core-js@1.2.7/library/fn/math/cosh.js",
      "npm:core-js@1.2.7/library/fn/math/expm1.js",
      "npm:core-js@1.2.7/library/fn/math/fround.js",
      "npm:core-js@1.2.7/library/fn/math/hypot.js",
      "npm:core-js@1.2.7/library/fn/math/imul.js",
      "npm:core-js@1.2.7/library/fn/math/index.js",
      "npm:core-js@1.2.7/library/fn/math/log10.js",
      "npm:core-js@1.2.7/library/fn/math/log1p.js",
      "npm:core-js@1.2.7/library/fn/math/log2.js",
      "npm:core-js@1.2.7/library/fn/math/sign.js",
      "npm:core-js@1.2.7/library/fn/math/sinh.js",
      "npm:core-js@1.2.7/library/fn/math/tanh.js",
      "npm:core-js@1.2.7/library/fn/math/trunc.js",
      "npm:core-js@1.2.7/library/fn/node-list.js",
      "npm:core-js@1.2.7/library/fn/node-list/index.js",
      "npm:core-js@1.2.7/library/fn/node-list/iterator.js",
      "npm:core-js@1.2.7/library/fn/number.js",
      "npm:core-js@1.2.7/library/fn/number/epsilon.js",
      "npm:core-js@1.2.7/library/fn/number/index.js",
      "npm:core-js@1.2.7/library/fn/number/is-finite.js",
      "npm:core-js@1.2.7/library/fn/number/is-integer.js",
      "npm:core-js@1.2.7/library/fn/number/is-nan.js",
      "npm:core-js@1.2.7/library/fn/number/is-safe-integer.js",
      "npm:core-js@1.2.7/library/fn/number/iterator.js",
      "npm:core-js@1.2.7/library/fn/number/max-safe-integer.js",
      "npm:core-js@1.2.7/library/fn/number/min-safe-integer.js",
      "npm:core-js@1.2.7/library/fn/number/parse-float.js",
      "npm:core-js@1.2.7/library/fn/number/parse-int.js",
      "npm:core-js@1.2.7/library/fn/object.js",
      "npm:core-js@1.2.7/library/fn/object/assign.js",
      "npm:core-js@1.2.7/library/fn/object/classof.js",
      "npm:core-js@1.2.7/library/fn/object/create.js",
      "npm:core-js@1.2.7/library/fn/object/define-properties.js",
      "npm:core-js@1.2.7/library/fn/object/define-property.js",
      "npm:core-js@1.2.7/library/fn/object/define.js",
      "npm:core-js@1.2.7/library/fn/object/entries.js",
      "npm:core-js@1.2.7/library/fn/object/freeze.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-descriptors.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-names.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-symbols.js",
      "npm:core-js@1.2.7/library/fn/object/get-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/object/index.js",
      "npm:core-js@1.2.7/library/fn/object/is-extensible.js",
      "npm:core-js@1.2.7/library/fn/object/is-frozen.js",
      "npm:core-js@1.2.7/library/fn/object/is-object.js",
      "npm:core-js@1.2.7/library/fn/object/is-sealed.js",
      "npm:core-js@1.2.7/library/fn/object/is.js",
      "npm:core-js@1.2.7/library/fn/object/keys.js",
      "npm:core-js@1.2.7/library/fn/object/make.js",
      "npm:core-js@1.2.7/library/fn/object/prevent-extensions.js",
      "npm:core-js@1.2.7/library/fn/object/seal.js",
      "npm:core-js@1.2.7/library/fn/object/set-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/object/values.js",
      "npm:core-js@1.2.7/library/fn/promise.js",
      "npm:core-js@1.2.7/library/fn/reflect.js",
      "npm:core-js@1.2.7/library/fn/reflect/apply.js",
      "npm:core-js@1.2.7/library/fn/reflect/construct.js",
      "npm:core-js@1.2.7/library/fn/reflect/define-property.js",
      "npm:core-js@1.2.7/library/fn/reflect/delete-property.js",
      "npm:core-js@1.2.7/library/fn/reflect/enumerate.js",
      "npm:core-js@1.2.7/library/fn/reflect/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/fn/reflect/get-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/reflect/get.js",
      "npm:core-js@1.2.7/library/fn/reflect/has.js",
      "npm:core-js@1.2.7/library/fn/reflect/index.js",
      "npm:core-js@1.2.7/library/fn/reflect/is-extensible.js",
      "npm:core-js@1.2.7/library/fn/reflect/own-keys.js",
      "npm:core-js@1.2.7/library/fn/reflect/prevent-extensions.js",
      "npm:core-js@1.2.7/library/fn/reflect/set-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/reflect/set.js",
      "npm:core-js@1.2.7/library/fn/regexp.js",
      "npm:core-js@1.2.7/library/fn/regexp/escape.js",
      "npm:core-js@1.2.7/library/fn/regexp/index.js",
      "npm:core-js@1.2.7/library/fn/set-immediate.js",
      "npm:core-js@1.2.7/library/fn/set-interval.js",
      "npm:core-js@1.2.7/library/fn/set-timeout.js",
      "npm:core-js@1.2.7/library/fn/set.js",
      "npm:core-js@1.2.7/library/fn/string.js",
      "npm:core-js@1.2.7/library/fn/string/at.js",
      "npm:core-js@1.2.7/library/fn/string/code-point-at.js",
      "npm:core-js@1.2.7/library/fn/string/ends-with.js",
      "npm:core-js@1.2.7/library/fn/string/escape-html.js",
      "npm:core-js@1.2.7/library/fn/string/from-code-point.js",
      "npm:core-js@1.2.7/library/fn/string/includes.js",
      "npm:core-js@1.2.7/library/fn/string/index.js",
      "npm:core-js@1.2.7/library/fn/string/iterator.js",
      "npm:core-js@1.2.7/library/fn/string/pad-left.js",
      "npm:core-js@1.2.7/library/fn/string/pad-right.js",
      "npm:core-js@1.2.7/library/fn/string/raw.js",
      "npm:core-js@1.2.7/library/fn/string/repeat.js",
      "npm:core-js@1.2.7/library/fn/string/starts-with.js",
      "npm:core-js@1.2.7/library/fn/string/trim-left.js",
      "npm:core-js@1.2.7/library/fn/string/trim-right.js",
      "npm:core-js@1.2.7/library/fn/string/trim.js",
      "npm:core-js@1.2.7/library/fn/string/unescape-html.js",
      "npm:core-js@1.2.7/library/fn/symbol.js",
      "npm:core-js@1.2.7/library/fn/symbol/for.js",
      "npm:core-js@1.2.7/library/fn/symbol/has-instance.js",
      "npm:core-js@1.2.7/library/fn/symbol/index.js",
      "npm:core-js@1.2.7/library/fn/symbol/is-concat-spreadable.js",
      "npm:core-js@1.2.7/library/fn/symbol/iterator.js",
      "npm:core-js@1.2.7/library/fn/symbol/key-for.js",
      "npm:core-js@1.2.7/library/fn/symbol/match.js",
      "npm:core-js@1.2.7/library/fn/symbol/replace.js",
      "npm:core-js@1.2.7/library/fn/symbol/search.js",
      "npm:core-js@1.2.7/library/fn/symbol/species.js",
      "npm:core-js@1.2.7/library/fn/symbol/split.js",
      "npm:core-js@1.2.7/library/fn/symbol/to-primitive.js",
      "npm:core-js@1.2.7/library/fn/symbol/to-string-tag.js",
      "npm:core-js@1.2.7/library/fn/symbol/unscopables.js",
      "npm:core-js@1.2.7/library/fn/weak-map.js",
      "npm:core-js@1.2.7/library/fn/weak-set.js",
      "npm:core-js@1.2.7/library/index.js",
      "npm:core-js@1.2.7/library/js.js",
      "npm:core-js@1.2.7/library/js/array.js",
      "npm:core-js@1.2.7/library/js/index.js",
      "npm:core-js@1.2.7/library/modules/$.a-function.js",
      "npm:core-js@1.2.7/library/modules/$.add-to-unscopables.js",
      "npm:core-js@1.2.7/library/modules/$.an-object.js",
      "npm:core-js@1.2.7/library/modules/$.array-copy-within.js",
      "npm:core-js@1.2.7/library/modules/$.array-fill.js",
      "npm:core-js@1.2.7/library/modules/$.array-includes.js",
      "npm:core-js@1.2.7/library/modules/$.array-methods.js",
      "npm:core-js@1.2.7/library/modules/$.array-species-create.js",
      "npm:core-js@1.2.7/library/modules/$.buffer.js",
      "npm:core-js@1.2.7/library/modules/$.classof.js",
      "npm:core-js@1.2.7/library/modules/$.cof.js",
      "npm:core-js@1.2.7/library/modules/$.collection-strong.js",
      "npm:core-js@1.2.7/library/modules/$.collection-to-json.js",
      "npm:core-js@1.2.7/library/modules/$.collection-weak.js",
      "npm:core-js@1.2.7/library/modules/$.collection.js",
      "npm:core-js@1.2.7/library/modules/$.core.js",
      "npm:core-js@1.2.7/library/modules/$.ctx.js",
      "npm:core-js@1.2.7/library/modules/$.defined.js",
      "npm:core-js@1.2.7/library/modules/$.descriptors.js",
      "npm:core-js@1.2.7/library/modules/$.dom-create.js",
      "npm:core-js@1.2.7/library/modules/$.enum-keys.js",
      "npm:core-js@1.2.7/library/modules/$.export.js",
      "npm:core-js@1.2.7/library/modules/$.fails-is-regexp.js",
      "npm:core-js@1.2.7/library/modules/$.fails.js",
      "npm:core-js@1.2.7/library/modules/$.fix-re-wks.js",
      "npm:core-js@1.2.7/library/modules/$.flags.js",
      "npm:core-js@1.2.7/library/modules/$.for-of.js",
      "npm:core-js@1.2.7/library/modules/$.get-names.js",
      "npm:core-js@1.2.7/library/modules/$.global.js",
      "npm:core-js@1.2.7/library/modules/$.has.js",
      "npm:core-js@1.2.7/library/modules/$.hide.js",
      "npm:core-js@1.2.7/library/modules/$.html.js",
      "npm:core-js@1.2.7/library/modules/$.invoke.js",
      "npm:core-js@1.2.7/library/modules/$.iobject.js",
      "npm:core-js@1.2.7/library/modules/$.is-array-iter.js",
      "npm:core-js@1.2.7/library/modules/$.is-array.js",
      "npm:core-js@1.2.7/library/modules/$.is-integer.js",
      "npm:core-js@1.2.7/library/modules/$.is-object.js",
      "npm:core-js@1.2.7/library/modules/$.is-regexp.js",
      "npm:core-js@1.2.7/library/modules/$.iter-call.js",
      "npm:core-js@1.2.7/library/modules/$.iter-create.js",
      "npm:core-js@1.2.7/library/modules/$.iter-define.js",
      "npm:core-js@1.2.7/library/modules/$.iter-detect.js",
      "npm:core-js@1.2.7/library/modules/$.iter-step.js",
      "npm:core-js@1.2.7/library/modules/$.iterators.js",
      "npm:core-js@1.2.7/library/modules/$.js",
      "npm:core-js@1.2.7/library/modules/$.keyof.js",
      "npm:core-js@1.2.7/library/modules/$.library.js",
      "npm:core-js@1.2.7/library/modules/$.math-expm1.js",
      "npm:core-js@1.2.7/library/modules/$.math-log1p.js",
      "npm:core-js@1.2.7/library/modules/$.math-sign.js",
      "npm:core-js@1.2.7/library/modules/$.microtask.js",
      "npm:core-js@1.2.7/library/modules/$.object-assign.js",
      "npm:core-js@1.2.7/library/modules/$.object-define.js",
      "npm:core-js@1.2.7/library/modules/$.object-sap.js",
      "npm:core-js@1.2.7/library/modules/$.object-to-array.js",
      "npm:core-js@1.2.7/library/modules/$.own-keys.js",
      "npm:core-js@1.2.7/library/modules/$.partial.js",
      "npm:core-js@1.2.7/library/modules/$.path.js",
      "npm:core-js@1.2.7/library/modules/$.property-desc.js",
      "npm:core-js@1.2.7/library/modules/$.redefine-all.js",
      "npm:core-js@1.2.7/library/modules/$.redefine.js",
      "npm:core-js@1.2.7/library/modules/$.replacer.js",
      "npm:core-js@1.2.7/library/modules/$.same-value.js",
      "npm:core-js@1.2.7/library/modules/$.set-proto.js",
      "npm:core-js@1.2.7/library/modules/$.set-species.js",
      "npm:core-js@1.2.7/library/modules/$.set-to-string-tag.js",
      "npm:core-js@1.2.7/library/modules/$.shared.js",
      "npm:core-js@1.2.7/library/modules/$.species-constructor.js",
      "npm:core-js@1.2.7/library/modules/$.strict-new.js",
      "npm:core-js@1.2.7/library/modules/$.string-at.js",
      "npm:core-js@1.2.7/library/modules/$.string-context.js",
      "npm:core-js@1.2.7/library/modules/$.string-pad.js",
      "npm:core-js@1.2.7/library/modules/$.string-repeat.js",
      "npm:core-js@1.2.7/library/modules/$.string-trim.js",
      "npm:core-js@1.2.7/library/modules/$.task.js",
      "npm:core-js@1.2.7/library/modules/$.to-index.js",
      "npm:core-js@1.2.7/library/modules/$.to-integer.js",
      "npm:core-js@1.2.7/library/modules/$.to-iobject.js",
      "npm:core-js@1.2.7/library/modules/$.to-length.js",
      "npm:core-js@1.2.7/library/modules/$.to-object.js",
      "npm:core-js@1.2.7/library/modules/$.to-primitive.js",
      "npm:core-js@1.2.7/library/modules/$.typed-array.js",
      "npm:core-js@1.2.7/library/modules/$.typed.js",
      "npm:core-js@1.2.7/library/modules/$.uid.js",
      "npm:core-js@1.2.7/library/modules/$.wks.js",
      "npm:core-js@1.2.7/library/modules/core.delay.js",
      "npm:core-js@1.2.7/library/modules/core.dict.js",
      "npm:core-js@1.2.7/library/modules/core.function.part.js",
      "npm:core-js@1.2.7/library/modules/core.get-iterator-method.js",
      "npm:core-js@1.2.7/library/modules/core.get-iterator.js",
      "npm:core-js@1.2.7/library/modules/core.is-iterable.js",
      "npm:core-js@1.2.7/library/modules/core.log.js",
      "npm:core-js@1.2.7/library/modules/core.number.iterator.js",
      "npm:core-js@1.2.7/library/modules/core.object.classof.js",
      "npm:core-js@1.2.7/library/modules/core.object.define.js",
      "npm:core-js@1.2.7/library/modules/core.object.is-object.js",
      "npm:core-js@1.2.7/library/modules/core.object.make.js",
      "npm:core-js@1.2.7/library/modules/core.string.escape-html.js",
      "npm:core-js@1.2.7/library/modules/core.string.unescape-html.js",
      "npm:core-js@1.2.7/library/modules/es5.js",
      "npm:core-js@1.2.7/library/modules/es6.array.copy-within.js",
      "npm:core-js@1.2.7/library/modules/es6.array.fill.js",
      "npm:core-js@1.2.7/library/modules/es6.array.find-index.js",
      "npm:core-js@1.2.7/library/modules/es6.array.find.js",
      "npm:core-js@1.2.7/library/modules/es6.array.from.js",
      "npm:core-js@1.2.7/library/modules/es6.array.iterator.js",
      "npm:core-js@1.2.7/library/modules/es6.array.of.js",
      "npm:core-js@1.2.7/library/modules/es6.array.species.js",
      "npm:core-js@1.2.7/library/modules/es6.date.to-string.js",
      "npm:core-js@1.2.7/library/modules/es6.function.has-instance.js",
      "npm:core-js@1.2.7/library/modules/es6.function.name.js",
      "npm:core-js@1.2.7/library/modules/es6.map.js",
      "npm:core-js@1.2.7/library/modules/es6.math.acosh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.asinh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.atanh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.cbrt.js",
      "npm:core-js@1.2.7/library/modules/es6.math.clz32.js",
      "npm:core-js@1.2.7/library/modules/es6.math.cosh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.expm1.js",
      "npm:core-js@1.2.7/library/modules/es6.math.fround.js",
      "npm:core-js@1.2.7/library/modules/es6.math.hypot.js",
      "npm:core-js@1.2.7/library/modules/es6.math.imul.js",
      "npm:core-js@1.2.7/library/modules/es6.math.log10.js",
      "npm:core-js@1.2.7/library/modules/es6.math.log1p.js",
      "npm:core-js@1.2.7/library/modules/es6.math.log2.js",
      "npm:core-js@1.2.7/library/modules/es6.math.sign.js",
      "npm:core-js@1.2.7/library/modules/es6.math.sinh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.tanh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.trunc.js",
      "npm:core-js@1.2.7/library/modules/es6.number.constructor.js",
      "npm:core-js@1.2.7/library/modules/es6.number.epsilon.js",
      "npm:core-js@1.2.7/library/modules/es6.number.is-finite.js",
      "npm:core-js@1.2.7/library/modules/es6.number.is-integer.js",
      "npm:core-js@1.2.7/library/modules/es6.number.is-nan.js",
      "npm:core-js@1.2.7/library/modules/es6.number.is-safe-integer.js",
      "npm:core-js@1.2.7/library/modules/es6.number.max-safe-integer.js",
      "npm:core-js@1.2.7/library/modules/es6.number.min-safe-integer.js",
      "npm:core-js@1.2.7/library/modules/es6.number.parse-float.js",
      "npm:core-js@1.2.7/library/modules/es6.number.parse-int.js",
      "npm:core-js@1.2.7/library/modules/es6.object.assign.js",
      "npm:core-js@1.2.7/library/modules/es6.object.freeze.js",
      "npm:core-js@1.2.7/library/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/es6.object.get-own-property-names.js",
      "npm:core-js@1.2.7/library/modules/es6.object.get-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/es6.object.is-extensible.js",
      "npm:core-js@1.2.7/library/modules/es6.object.is-frozen.js",
      "npm:core-js@1.2.7/library/modules/es6.object.is-sealed.js",
      "npm:core-js@1.2.7/library/modules/es6.object.is.js",
      "npm:core-js@1.2.7/library/modules/es6.object.keys.js",
      "npm:core-js@1.2.7/library/modules/es6.object.prevent-extensions.js",
      "npm:core-js@1.2.7/library/modules/es6.object.seal.js",
      "npm:core-js@1.2.7/library/modules/es6.object.set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/es6.object.to-string.js",
      "npm:core-js@1.2.7/library/modules/es6.promise.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.apply.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.construct.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.define-property.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.delete-property.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.enumerate.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.get-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.get.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.has.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.is-extensible.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.own-keys.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.prevent-extensions.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.set.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.constructor.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.flags.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.match.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.replace.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.search.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.split.js",
      "npm:core-js@1.2.7/library/modules/es6.set.js",
      "npm:core-js@1.2.7/library/modules/es6.string.code-point-at.js",
      "npm:core-js@1.2.7/library/modules/es6.string.ends-with.js",
      "npm:core-js@1.2.7/library/modules/es6.string.from-code-point.js",
      "npm:core-js@1.2.7/library/modules/es6.string.includes.js",
      "npm:core-js@1.2.7/library/modules/es6.string.iterator.js",
      "npm:core-js@1.2.7/library/modules/es6.string.raw.js",
      "npm:core-js@1.2.7/library/modules/es6.string.repeat.js",
      "npm:core-js@1.2.7/library/modules/es6.string.starts-with.js",
      "npm:core-js@1.2.7/library/modules/es6.string.trim.js",
      "npm:core-js@1.2.7/library/modules/es6.symbol.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.array-buffer.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.data-view.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.float32-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.float64-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.int16-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.int32-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.int8-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.uint16-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.uint32-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.uint8-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.uint8-clamped-array.js",
      "npm:core-js@1.2.7/library/modules/es6.weak-map.js",
      "npm:core-js@1.2.7/library/modules/es6.weak-set.js",
      "npm:core-js@1.2.7/library/modules/es7.array.includes.js",
      "npm:core-js@1.2.7/library/modules/es7.map.to-json.js",
      "npm:core-js@1.2.7/library/modules/es7.object.entries.js",
      "npm:core-js@1.2.7/library/modules/es7.object.get-own-property-descriptors.js",
      "npm:core-js@1.2.7/library/modules/es7.object.values.js",
      "npm:core-js@1.2.7/library/modules/es7.regexp.escape.js",
      "npm:core-js@1.2.7/library/modules/es7.set.to-json.js",
      "npm:core-js@1.2.7/library/modules/es7.string.at.js",
      "npm:core-js@1.2.7/library/modules/es7.string.pad-left.js",
      "npm:core-js@1.2.7/library/modules/es7.string.pad-right.js",
      "npm:core-js@1.2.7/library/modules/es7.string.trim-left.js",
      "npm:core-js@1.2.7/library/modules/es7.string.trim-right.js",
      "npm:core-js@1.2.7/library/modules/js.array.statics.js",
      "npm:core-js@1.2.7/library/modules/web.dom.iterable.js",
      "npm:core-js@1.2.7/library/modules/web.immediate.js",
      "npm:core-js@1.2.7/library/modules/web.timers.js",
      "npm:core-js@1.2.7/library/shim.js",
      "npm:core-js@1.2.7/library/web.js",
      "npm:core-js@1.2.7/library/web/dom.js",
      "npm:core-js@1.2.7/library/web/immediate.js",
      "npm:core-js@1.2.7/library/web/index.js",
      "npm:core-js@1.2.7/library/web/timers.js",
      "npm:process@0.11.10.js",
      "npm:process@0.11.10/browser.js",
      "npm:showdown@1.9.1.js",
      "npm:showdown@1.9.1/dist/showdown.js",
      "npm:showdown@1.9.1/dist/showdown.min.js",
      "settings.js",
      "shared/au-code.js",
      "shared/collapse-panel.html!github:systemjs/plugin-text@0.0.4.js",
      "shared/collapse-panel.js",
      "shared/gist-list.html!github:systemjs/plugin-text@0.0.4.js",
      "shared/gist-list.js",
      "shared/logger.html!github:systemjs/plugin-text@0.0.4.js",
      "shared/logger.js",
      "shared/markdown.js",
      "shared/signalr.js",
      "shared/theme-manager.js",
      "theme-selector/theme-selector.html!github:systemjs/plugin-text@0.0.4.js",
      "theme-selector/theme-selector.js"
    ]
  }
});